### PR TITLE
Fix several issues

### LINKED ISSUE #28: 关于用户名显示的一些改进
### What problem does this feature solve?
注销登录在手机上没法显示，因为点击后就直接注销了，很突然。

### What does the proposed API look like?
点用户名后出现dropdown，里面放一个选项“注销”？
另外希望增加旧版的对用户ID的说明。

### PR DESCRIPTION
**Pull request by GalvinGao**
## UI
* Fixed #28, #33, #34

## API
* Optimized `objectManager`
* Isolated `AccountManager` from `App.vue`

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -284,6 +216,20 @@
...
...08 31.86 31.86 0 0 1-24.43.03 32.19 32.19 0 0 1-10.4-7.03A31.39 31.39 0 0 1 5.5 28.5c0-4.23.8-8.3 2.43-12.2 1.62-3.9 3.97-7.4 7.06-10.49C21.07-.39 28.56-3.5 37.44-3.5zm.12 5.77c-7.32 0-13.47 2.56-18.46 7.66a27.51 27.51 0 0 0-5.8 8.6 25.2 25.2 0 0 0-2.03 9.97c0 3.43.68 6.73 2.03 9.91a26.5 26.5 0 0 0 5.8 8.52c2.51 2.5 5.35 4.4 8.51 5.71a25.83 25.83 0 0 0 19.92-.03 27.64 27.64 0 0 0 8.71-5.76c5-4.88 7.49-11 7.49-18.35 0-3.54-.65-6.9-1.95-10.06A25.59 25.59 0 0 0 56.13 10a25.32 25.32 0 0 0-18.57-7.72zm-.4 20.92l-4.3 2.23a4.4 4.4 0 0 0-1.68-2 3.8 3.8 0 0 0-1.85-.58c-2.86 0-4.29 1.89-4.29 5.66 0 1.72.36 3.09 1.08 4.11a3.66 3.66 0 0 0 3.2 1.55c1.87 0 3.19-.92 3.95-2.74l3.94 2a9.4 9.4 0 0 1-8.4 5.02c-2.85 0-5.16-.87-6.91-2.62-1.75-1.76-2.63-4.2-2.63-7.32 0-3.05.89-5.46 2.66-7.25a9.05 9.05 0 0 1 6.71-2.69c3.96 0 6.8 1.54 8.52 4.63zm18.45 0l-4.23 2.23a4.4 4.4 0 0 0-1.68-2 3.89 3.89 0 0 0-1.92-.58c-2.85 0-4.28 1.89-4.28 5.66 0 1.72.36 3.09 1.08 4.11a3.66 3.66 0 0 0 3.2 1.55c1.87 0 3.18-.92 3.94-2.74l4 2a9.82 9.82 0 0 1-3.54 3.68 9.23 9.23 0 0 1-4.85 1.34c-2.9 0-5.21-.87-6.94-2.62-1.74-1.76-2.6-4.2-2.6-7.32 0-3.05.88-5.46 2.65-7.25a9.05 9.05 0 0 1 6.72-2.69c3.96 0 6.78 1.54 8.45 4.63z" /></svg>
```
Comment (AsahiLuna) [inline src/App.vue]: I recommend use SVG file not write code in HTML template, it’s hard to read.

Comment (GalvinGao) [reply src/App.vue]: no problem. I will isolate the SVG into separated file under `src/assets/ccIcons` 😄

Comment (GalvinGao) [reply src/App.vue]: I've forgot to do this... I'll open a new issue in order to track this.
