### PR TITLE
fix(router): change the page title according its actual page title

### LINKED ISSUE #76: Page title is not changing
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

### URL
`http://localhost:8080`

### Steps to reproduce
1. Launch the page
2. Go to any other page rather than the home page

### What is expected?
The title of the corresponding page appears on the title bar (controlled by `document.title`)

### What is actually happening?
The default title, not changing.

### PR DESCRIPTION
**Pull request by GalvinGao**
change the page title according its actual page title, while also complies with i18n

fix #76

### CODE REVIEW

File: src/router.js [hunk 1]
```diff
@@ -220,4 +223,11 @@ export default new Router({
       ]
     }
   ]
-})
\ No newline at end of file
+});
+
+router.beforeEach((to, from, next) => {
```
Comment (AsahiLuna) [inline src/router.js]: My fault, this method already defined in main.js, could you refactor this code?

Comment (GalvinGao) [reply src/router.js]: fixed ❤️
